#eureka:
#    client:
#        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
server:
    port: 80
spring:
    application:
        name: spring-boot-client
#    cloud:
#        config:
#          label: master
#          profile: dev
#          uri: http://localhost:8888